language: objective-c
osx_image: xcode8.2
addons:
  firefox: latest
  ssh_known_hosts:
  - github.com
  - bitbucket.org
before_script:
  - echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config  
before_install:
  - openssl aes-256-cbc -K $encrypted_b06a8d276963_key -iv $encrypted_b06a8d276963_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - mv id_rsa ~/.ssh/id_rsa
  - ./before_script.sh

script: ./build.sh

after_failure:
  - cat ~/Library/Logs/CoreSimulator/**/system.log
  - cat iosoutput.log
