language: objective-c
osx_image: xcode8.2
before_install:
  - brew remove git
  - brew remove curl
  - brew install openssl
  - brew install --with-openssl curl
  - brew install --with-brewed-curl --with-brewed-openssl git
  - brew update
  - brew install mongodb
  - brew services start mongodb
  - brew install mysql
  - mysql.server start
  - brew install ant
  - git clone https://github.com/MobilityFirst/GNS
  - cd GNS
  - ant
  - ./bin/gpServer.sh start all
  - cd ..
script: ./build.sh
