language: objective-c
osx_image: xcode8.2
addons:
  firefox: latest
  ssh_known_hosts:
  - github.com
  - bitbucket.com
  - bitbucket.org
before_install:
  - openssl aes-256-cbc -K $encrypted_b06a8d276963_key -iv $encrypted_b06a8d276963_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - mv id_rsa ~/.ssh/id_rsa
  - brew update
  - brew install lyft/formulae/set-simulator-location
  - brew install homebrew/dupes/expect
  - sudo gem install xcpretty
  - brew install mongodb
  - brew services start mongodb
  - brew install ant
  - git config --global http.postBuffer 1048576000
  - GIT_CURL_VERBOSE=1 git clone --depth=1 https://github.com/MobilityFirst/GNS
  - cd GNS
  - ant
  - ./bin/gpServer.sh start all
  - cd ..
  - brew install mysql
  - mysql.server start
  - mysql -u root -e "CREATE USER 'emportalUser'@'localhost' IDENTIFIED BY 'some_pass';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'emportalUser'@'localhost' WITH GRANT OPTION;"
  - mysql -u root -e "create database emportal;"
  - brew tap homebrew/homebrew-php
  - brew install php56
  - brew install composer
  - rm -rf em_portal
  - git clone git@bitbucket.org:danielsamfdo/em_portal.git
  - cd em_portal
  - cp ../custom_files/auspice.js public/js/
  - composer update
  - composer install
  - php artisan migrate
  - php artisan serve &
  - cd ..
  - touch iosoutput.log  && ./logger.sh &
  - sudo pip install selenium &
  - python commandserver.py localhost 5555 &

script: ./build.sh

after_script:
  - ./image_upload.sh *.png
after_failure:
  - cat ~/Library/Logs/CoreSimulator/**/system.log
  - cat iosoutput.log
