# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'


target "UMassEmergency" do
pod "AFNetworking", "~> 2.6"
pod "XMLDictionary"
pod "iCarousel"
pod "Google/Analytics"
end
